name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
    paths:
      - 'hardware/*.kicad_sch'
      - 'hardware/*.kicad_pcb'
      - '.github/workflows/ecad_ci.yml'
  pull_request:
    branches: [ master ]
    paths:
      - 'hardware/*.kicad_sch'
      - 'hardware/*.kicad_pcb'
      - '.github/workflows/ecad_ci.yml'      

jobs:

  testing_kibot:
    name: ERC/DRC/Production
    runs-on: ubuntu-latest
    container: setsoft/kicad_auto:ki6.0.10_Debian

    steps:
    - name: Checkout repository   
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.PAT_SECRET }}
        submodules: true

    - name: Run ERC/DRC/Production
      run: |
        kibot -e hardware/board.kicad_sch -b hardware/board.kicad_pcb -c ci/utils/board.kibot.yaml


  testing_part_numbers:
    name: Part numbers check
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository   
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.PAT_SECRET }}
        submodules: true

    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
  
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install glob2
        pip install requests
        pip install pandas

    - name: Perform check
      run: |
        python ci/utils/check_assembly_ready.py -c -s 'Bottom'
        python ci/utils/check_assembly_ready.py -c -s 'Top'

